// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI2XHOuBHHFj_UpqXzXKywlhJZP9qjz_I',
    appId: '1:1052501904643:web:8c39038962af2a7cc32d36',
    messagingSenderId: '1052501904643',
    projectId: 'wscubetech-402d0',
    authDomain: 'wscubetech-402d0.firebaseapp.com',
    storageBucket: 'wscubetech-402d0.appspot.com',
    measurementId: 'G-1DJH14CDWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuhi-eKdYPPT9qHM-HopTiJrL7ocJyphk',
    appId: '1:1052501904643:android:786e373d72b1c8ecc32d36',
    messagingSenderId: '1052501904643',
    projectId: 'wscubetech-402d0',
    storageBucket: 'wscubetech-402d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaoMTqjPbwocgbWIayuNodDwBt1fLiRNY',
    appId: '1:1052501904643:ios:1f543c1582d95956c32d36',
    messagingSenderId: '1052501904643',
    projectId: 'wscubetech-402d0',
    storageBucket: 'wscubetech-402d0.appspot.com',
    iosBundleId: 'com.example.wscubetech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaoMTqjPbwocgbWIayuNodDwBt1fLiRNY',
    appId: '1:1052501904643:ios:70aa22c2cd6c70b4c32d36',
    messagingSenderId: '1052501904643',
    projectId: 'wscubetech-402d0',
    storageBucket: 'wscubetech-402d0.appspot.com',
    iosBundleId: 'com.example.wscubetech.RunnerTests',
  );
}
